# Generated by Django 5.1 on 2024-10-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_colour_remove_product_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_color',
            new_name='product_colour',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_method', to='app.paymentmethod'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather Not Say', 'Rather Not Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather Not Say', 'Rather Not Say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_for_customer', to='app.customer'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='app.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
